### ISSUE TITLE
Retrieving tweets

### ISSUE THREAD

**Issue by tinthtoo** [ropensci/rAltmetric#15]
Dear rAltmetric developer(s)
Thank you very much for developing this very useful package. As altmetric research grows, people are looking into content analysis of tweets, Facebook comments, etc. For my case, it's tweets.  So, it would be great if we could also retrieve tweets of articles based on DOI with rAltmetric.
Thanks and regards
Tint

**Comment by karthik** [comment]
Starting to work on this now, @tinthtoo

**Comment by karthik** [comment]
The API does not provide this information. If you find that it does, please point me to the documentation and I'll add it.
